// Spring Boot endpoint that handles Gemini requests.
const GEMINI_URL = "http://localhost:8080/gemini";

export async function getNonnaMessage({
  state,
  ingredientCount,
  selectedIngredients
}) {
  // Convert the selected ingredient objects into just their names.
  const ingredients = (selectedIngredients || []).map(
    ingredient => ingredient.name
  );

  // Send the request to the Spring Boot backend.
  const response = await fetch(GEMINI_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      state,
      ingredientCount,
      ingredients
    })
  });

  /*
   * If Spring Boot returns an error, try to read the response body.
   *
   * This gives us more useful information than simply seeing
   * "500 Internal Server Error" in the browser console.
   */
  if (!response.ok) {
    let errorDetails = "";

    try {
      errorDetails = await response.text();
    } catch {
      errorDetails = "";
    }

    throw new Error(
      `Nonna request failed: ${response.status}${
        errorDetails ? ` - ${errorDetails}` : ""
      }`
    );
  }

  // Convert the successful response into JavaScript.
  const data = await response.json();

  // Return the message generated by Gemini.
  return data.message;
}
