spring.application.name=nonna

spring.datasource.url=jdbc:mysql://localhost:3306/nonna?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=update
